/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as ShellUnauthorizedRouteImport } from './routes/_shell.unauthorized'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellReportsRouteImport } from './routes/_shell.reports'
import { Route as ShellProfileRouteImport } from './routes/_shell.profile'
import { Route as ShellNotificationsRouteImport } from './routes/_shell.notifications'
import { Route as ShellMastersRouteImport } from './routes/_shell.masters'
import { Route as ShellHelpRouteImport } from './routes/_shell.help'
import { Route as ShellApprovalsRouteImport } from './routes/_shell.approvals'
import { Route as ShellUsersIndexRouteImport } from './routes/_shell.users.index'
import { Route as ShellRequestsIndexRouteImport } from './routes/_shell.requests.index'
import { Route as ShellAssetsIndexRouteImport } from './routes/_shell.assets.index'
import { Route as ShellUsersUserIdRouteImport } from './routes/_shell.users.$userId'
import { Route as ShellRequestsNewRouteImport } from './routes/_shell.requests.new'
import { Route as ShellAssetsAssetIdRouteImport } from './routes/_shell.assets.$assetId'
import { Route as ShellRequestsRequestIdIndexRouteImport } from './routes/_shell.requests.$requestId.index'
import { Route as ShellRequestsRequestIdEditRouteImport } from './routes/_shell.requests.$requestId.edit'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellUnauthorizedRoute = ShellUnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReportsRoute = ShellReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProfileRoute = ShellProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ShellRoute,
} as any)
const ShellNotificationsRoute = ShellNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMastersRoute = ShellMastersRouteImport.update({
  id: '/masters',
  path: '/masters',
  getParentRoute: () => ShellRoute,
} as any)
const ShellHelpRoute = ShellHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => ShellRoute,
} as any)
const ShellApprovalsRoute = ShellApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => ShellRoute,
} as any)
const ShellUsersIndexRoute = ShellUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRequestsIndexRoute = ShellRequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAssetsIndexRoute = ShellAssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellUsersUserIdRoute = ShellUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRequestsNewRoute = ShellRequestsNewRouteImport.update({
  id: '/requests/new',
  path: '/requests/new',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAssetsAssetIdRoute = ShellAssetsAssetIdRouteImport.update({
  id: '/assets/$assetId',
  path: '/assets/$assetId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRequestsRequestIdIndexRoute =
  ShellRequestsRequestIdIndexRouteImport.update({
    id: '/requests/$requestId/',
    path: '/requests/$requestId/',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellRequestsRequestIdEditRoute =
  ShellRequestsRequestIdEditRouteImport.update({
    id: '/requests/$requestId/edit',
    path: '/requests/$requestId/edit',
    getParentRoute: () => ShellRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/approvals': typeof ShellApprovalsRoute
  '/help': typeof ShellHelpRoute
  '/masters': typeof ShellMastersRoute
  '/notifications': typeof ShellNotificationsRoute
  '/profile': typeof ShellProfileRoute
  '/reports': typeof ShellReportsRoute
  '/settings': typeof ShellSettingsRoute
  '/unauthorized': typeof ShellUnauthorizedRoute
  '/assets/$assetId': typeof ShellAssetsAssetIdRoute
  '/requests/new': typeof ShellRequestsNewRoute
  '/users/$userId': typeof ShellUsersUserIdRoute
  '/assets/': typeof ShellAssetsIndexRoute
  '/requests/': typeof ShellRequestsIndexRoute
  '/users/': typeof ShellUsersIndexRoute
  '/requests/$requestId/edit': typeof ShellRequestsRequestIdEditRoute
  '/requests/$requestId/': typeof ShellRequestsRequestIdIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/approvals': typeof ShellApprovalsRoute
  '/help': typeof ShellHelpRoute
  '/masters': typeof ShellMastersRoute
  '/notifications': typeof ShellNotificationsRoute
  '/profile': typeof ShellProfileRoute
  '/reports': typeof ShellReportsRoute
  '/settings': typeof ShellSettingsRoute
  '/unauthorized': typeof ShellUnauthorizedRoute
  '/': typeof ShellIndexRoute
  '/assets/$assetId': typeof ShellAssetsAssetIdRoute
  '/requests/new': typeof ShellRequestsNewRoute
  '/users/$userId': typeof ShellUsersUserIdRoute
  '/assets': typeof ShellAssetsIndexRoute
  '/requests': typeof ShellRequestsIndexRoute
  '/users': typeof ShellUsersIndexRoute
  '/requests/$requestId/edit': typeof ShellRequestsRequestIdEditRoute
  '/requests/$requestId': typeof ShellRequestsRequestIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_shell/approvals': typeof ShellApprovalsRoute
  '/_shell/help': typeof ShellHelpRoute
  '/_shell/masters': typeof ShellMastersRoute
  '/_shell/notifications': typeof ShellNotificationsRoute
  '/_shell/profile': typeof ShellProfileRoute
  '/_shell/reports': typeof ShellReportsRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/unauthorized': typeof ShellUnauthorizedRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/assets/$assetId': typeof ShellAssetsAssetIdRoute
  '/_shell/requests/new': typeof ShellRequestsNewRoute
  '/_shell/users/$userId': typeof ShellUsersUserIdRoute
  '/_shell/assets/': typeof ShellAssetsIndexRoute
  '/_shell/requests/': typeof ShellRequestsIndexRoute
  '/_shell/users/': typeof ShellUsersIndexRoute
  '/_shell/requests/$requestId/edit': typeof ShellRequestsRequestIdEditRoute
  '/_shell/requests/$requestId/': typeof ShellRequestsRequestIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/approvals'
    | '/help'
    | '/masters'
    | '/notifications'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/unauthorized'
    | '/assets/$assetId'
    | '/requests/new'
    | '/users/$userId'
    | '/assets/'
    | '/requests/'
    | '/users/'
    | '/requests/$requestId/edit'
    | '/requests/$requestId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/approvals'
    | '/help'
    | '/masters'
    | '/notifications'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/unauthorized'
    | '/'
    | '/assets/$assetId'
    | '/requests/new'
    | '/users/$userId'
    | '/assets'
    | '/requests'
    | '/users'
    | '/requests/$requestId/edit'
    | '/requests/$requestId'
  id:
    | '__root__'
    | '/_shell'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/_shell/approvals'
    | '/_shell/help'
    | '/_shell/masters'
    | '/_shell/notifications'
    | '/_shell/profile'
    | '/_shell/reports'
    | '/_shell/settings'
    | '/_shell/unauthorized'
    | '/_shell/'
    | '/_shell/assets/$assetId'
    | '/_shell/requests/new'
    | '/_shell/users/$userId'
    | '/_shell/assets/'
    | '/_shell/requests/'
    | '/_shell/users/'
    | '/_shell/requests/$requestId/edit'
    | '/_shell/requests/$requestId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/unauthorized': {
      id: '/_shell/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof ShellUnauthorizedRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/reports': {
      id: '/_shell/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ShellReportsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/profile': {
      id: '/_shell/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ShellProfileRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/notifications': {
      id: '/_shell/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof ShellNotificationsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/masters': {
      id: '/_shell/masters'
      path: '/masters'
      fullPath: '/masters'
      preLoaderRoute: typeof ShellMastersRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/help': {
      id: '/_shell/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof ShellHelpRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/approvals': {
      id: '/_shell/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ShellApprovalsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/users/': {
      id: '/_shell/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof ShellUsersIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/requests/': {
      id: '/_shell/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof ShellRequestsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/assets/': {
      id: '/_shell/assets/'
      path: '/assets'
      fullPath: '/assets/'
      preLoaderRoute: typeof ShellAssetsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/users/$userId': {
      id: '/_shell/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof ShellUsersUserIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/requests/new': {
      id: '/_shell/requests/new'
      path: '/requests/new'
      fullPath: '/requests/new'
      preLoaderRoute: typeof ShellRequestsNewRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/assets/$assetId': {
      id: '/_shell/assets/$assetId'
      path: '/assets/$assetId'
      fullPath: '/assets/$assetId'
      preLoaderRoute: typeof ShellAssetsAssetIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/requests/$requestId/': {
      id: '/_shell/requests/$requestId/'
      path: '/requests/$requestId'
      fullPath: '/requests/$requestId/'
      preLoaderRoute: typeof ShellRequestsRequestIdIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/requests/$requestId/edit': {
      id: '/_shell/requests/$requestId/edit'
      path: '/requests/$requestId/edit'
      fullPath: '/requests/$requestId/edit'
      preLoaderRoute: typeof ShellRequestsRequestIdEditRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellApprovalsRoute: typeof ShellApprovalsRoute
  ShellHelpRoute: typeof ShellHelpRoute
  ShellMastersRoute: typeof ShellMastersRoute
  ShellNotificationsRoute: typeof ShellNotificationsRoute
  ShellProfileRoute: typeof ShellProfileRoute
  ShellReportsRoute: typeof ShellReportsRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellUnauthorizedRoute: typeof ShellUnauthorizedRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellAssetsAssetIdRoute: typeof ShellAssetsAssetIdRoute
  ShellRequestsNewRoute: typeof ShellRequestsNewRoute
  ShellUsersUserIdRoute: typeof ShellUsersUserIdRoute
  ShellAssetsIndexRoute: typeof ShellAssetsIndexRoute
  ShellRequestsIndexRoute: typeof ShellRequestsIndexRoute
  ShellUsersIndexRoute: typeof ShellUsersIndexRoute
  ShellRequestsRequestIdEditRoute: typeof ShellRequestsRequestIdEditRoute
  ShellRequestsRequestIdIndexRoute: typeof ShellRequestsRequestIdIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellApprovalsRoute: ShellApprovalsRoute,
  ShellHelpRoute: ShellHelpRoute,
  ShellMastersRoute: ShellMastersRoute,
  ShellNotificationsRoute: ShellNotificationsRoute,
  ShellProfileRoute: ShellProfileRoute,
  ShellReportsRoute: ShellReportsRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellUnauthorizedRoute: ShellUnauthorizedRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellAssetsAssetIdRoute: ShellAssetsAssetIdRoute,
  ShellRequestsNewRoute: ShellRequestsNewRoute,
  ShellUsersUserIdRoute: ShellUsersUserIdRoute,
  ShellAssetsIndexRoute: ShellAssetsIndexRoute,
  ShellRequestsIndexRoute: ShellRequestsIndexRoute,
  ShellUsersIndexRoute: ShellUsersIndexRoute,
  ShellRequestsRequestIdEditRoute: ShellRequestsRequestIdEditRoute,
  ShellRequestsRequestIdIndexRoute: ShellRequestsRequestIdIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.jsx'
import type { startInstance } from './start.js'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
