/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as ShellApprovalsRouteImport } from './routes/_shell.approvals'
import { Route as ShellHelpRouteImport } from './routes/_shell.help'
import { Route as ShellMastersRouteImport } from './routes/_shell.masters'
import { Route as ShellNotificationsRouteImport } from './routes/_shell.notifications'
import { Route as ShellProfileRouteImport } from './routes/_shell.profile'
import { Route as ShellReportsRouteImport } from './routes/_shell.reports'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellUnauthorizedRouteImport } from './routes/_shell.unauthorized'
import { Route as ShellAssetsIndexRouteImport } from './routes/_shell.assets.index'
import { Route as ShellAssetsAssetIdRouteImport } from './routes/_shell.assets.$assetId'
import { Route as ShellRequestsIndexRouteImport } from './routes/_shell.requests.index'
import { Route as ShellRequestsNewRouteImport } from './routes/_shell.requests.new'
import { Route as ShellUsersIndexRouteImport } from './routes/_shell.users.index'
import { Route as ShellUsersUserIdRouteImport } from './routes/_shell.users.$userId'
import { Route as ShellRequestsRequestIdIndexRouteImport } from './routes/_shell.requests.$requestId.index'
import { Route as ShellRequestsRequestIdEditRouteImport } from './routes/_shell.requests.$requestId.edit'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
})
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
})
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
})
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
})
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
})
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
})
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
})
const ShellApprovalsRoute = ShellApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => ShellRoute,
})
const ShellHelpRoute = ShellHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => ShellRoute,
})
const ShellMastersRoute = ShellMastersRouteImport.update({
  id: '/masters',
  path: '/masters',
  getParentRoute: () => ShellRoute,
})
const ShellNotificationsRoute = ShellNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ShellRoute,
})
const ShellProfileRoute = ShellProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ShellRoute,
})
const ShellReportsRoute = ShellReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ShellRoute,
})
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
})
const ShellUnauthorizedRoute = ShellUnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => ShellRoute,
})
const ShellAssetsIndexRoute = ShellAssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => ShellRoute,
})
const ShellAssetsAssetIdRoute = ShellAssetsAssetIdRouteImport.update({
  id: '/assets/$assetId',
  path: '/assets/$assetId',
  getParentRoute: () => ShellRoute,
})
const ShellRequestsIndexRoute = ShellRequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => ShellRoute,
})
const ShellRequestsNewRoute = ShellRequestsNewRouteImport.update({
  id: '/requests/new',
  path: '/requests/new',
  getParentRoute: () => ShellRoute,
})
const ShellUsersIndexRoute = ShellUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => ShellRoute,
})
const ShellUsersUserIdRoute = ShellUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => ShellRoute,
})
const ShellRequestsRequestIdIndexRoute =
  ShellRequestsRequestIdIndexRouteImport.update({
    id: '/requests/$requestId/',
    path: '/requests/$requestId/',
    getParentRoute: () => ShellRoute,
  })
const ShellRequestsRequestIdEditRoute =
  ShellRequestsRequestIdEditRouteImport.update({
    id: '/requests/$requestId/edit',
    path: '/requests/$requestId/edit',
    getParentRoute: () => ShellRoute,
  })

const ShellRouteChildren = {
  ShellApprovalsRoute: ShellApprovalsRoute,
  ShellHelpRoute: ShellHelpRoute,
  ShellMastersRoute: ShellMastersRoute,
  ShellNotificationsRoute: ShellNotificationsRoute,
  ShellProfileRoute: ShellProfileRoute,
  ShellReportsRoute: ShellReportsRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellUnauthorizedRoute: ShellUnauthorizedRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellAssetsAssetIdRoute: ShellAssetsAssetIdRoute,
  ShellRequestsNewRoute: ShellRequestsNewRoute,
  ShellUsersUserIdRoute: ShellUsersUserIdRoute,
  ShellAssetsIndexRoute: ShellAssetsIndexRoute,
  ShellRequestsIndexRoute: ShellRequestsIndexRoute,
  ShellUsersIndexRoute: ShellUsersIndexRoute,
  ShellRequestsRequestIdEditRoute: ShellRequestsRequestIdEditRoute,
  ShellRequestsRequestIdIndexRoute: ShellRequestsRequestIdIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)
